import pandas as pd
import numpy as np
from pathlib import Path
import calendar


def _infer_pressure_pa(series: pd.Series) -> pd.Series:
    """Ensure station pressure is in Pa. If values look like hPa, convert."""
    s = series.copy()
    if s.dropna().mean() < 2000:  # likely hPa
        s = s * 100.0
    return s


def _dewpoint_from_t_rh(temp_c: pd.Series, rh_pct: pd.Series) -> pd.Series:
    """Compute dew point (°C) from temperature (°C) and relative humidity (%). Magnus formula."""
    # Avoid zeros/negatives
    rh = rh_pct.clip(lower=0.1, upper=100.0) / 100.0
    T = temp_c
    # Constants for water (over water, 0-60C)
    a = 17.27
    b = 237.7
    alpha = ((a * T) / (b + T)) + np.log(rh)
    Td = (b * alpha) / (a - alpha)
    return pd.Series(Td, index=temp_c.index)

def _epw_header(location: str = "LosAngeles-CA-USA", lat: float = 34.05, lon: float = -118.25,
                tz: float = -8.0, elevation_m: float = 89.0) -> str:
    # Minimal EPW headers (8 lines + data periods)
    lines = []
    # LOCATION,City,State,Country,Source,WMO,Lat,Lon,TimeZone,Elevation
    lines.append(
        f"LOCATION,{location},California,USA,pEPW,000000,{lat:.3f},{lon:.3f},{tz:.1f},{elevation_m:.1f}"
    )
    lines.append("DESIGN CONDITIONS,0")
    lines.append("TYPICAL/EXTREME PERIODS,0")
    lines.append("GROUND TEMPERATURES,0")
    lines.append("HOLIDAYS/DAYLIGHT SAVINGS,No,0,0,0")
    lines.append("COMMENTS 1,Generated by pEPW V4 Hybrid RS-VAR pipeline")
    lines.append("COMMENTS 2,Do not use for safety-critical design without verification")
    lines.append("DATA PERIODS,1,1,Data,Sunday, 1/ 1,12/31")
    return "\n".join(lines) + "\n"


def _write_epw_for_year(
    df: pd.DataFrame,
    year: int,
    out_path: Path,
    *,
    location: str = "LosAngeles-CA-USA",
    lat: float = 34.05,
    lon: float = -118.25,
    tz: float = -8.0,
    elevation_m: float = 89.0,
) -> None:
    """Write a single-year EPW (8760 hours) with data validation and cleaning. Drops Feb 29 if present."""
    # Select year and drop Feb 29 to enforce 8760 rows
    year_df = df.loc[str(year)]
    # Drop leap day (Feb 29) if present
    mask_leap = ~((year_df.index.month == 2) & (year_df.index.day == 29))
    year_df = year_df.loc[mask_leap]

    # Ensure exactly 8760 hours
    # If missing hours, forward-fill
    desired_index = pd.date_range(f"{year}-01-01 00:00", f"{year}-12-31 23:00", freq="h")
    if calendar.isleap(year):
        desired_index = desired_index[~((desired_index.month == 2) & (desired_index.day == 29))]
    year_df = year_df.reindex(desired_index)
    year_df.ffill(inplace=True)
    year_df.bfill(inplace=True)

    # Prepare required EPW columns with basic physical validation
    temp_c = year_df.get("temp")
    if temp_c is None:
        raise ValueError("Forecast output missing 'temp' column.")

    rh = year_df.get("relative_humidity")
    if rh is None:
        # fallback: assume 50% if RH not available
        rh = pd.Series(50.0, index=year_df.index)
    # Basic validation: relative humidity 0-100%
    rh = rh.clip(0, 100)

    # Dewpoint from T & RH (°C)
    dew_c = _dewpoint_from_t_rh(temp_c, rh)

    # Pressure in Pa - no artificial limits, just unit conversion if needed
    pressure_pa = year_df.get("pressure")
    if pressure_pa is None:
        # Fallback to 101325 Pa
        pressure_pa = pd.Series(101325.0, index=year_df.index)
    else:
        pressure_pa = _infer_pressure_pa(pressure_pa)

    # Wind with basic physical validation
    wind_speed = year_df.get("wind_speed", pd.Series(0.0, index=year_df.index))
    wind_dir = year_df.get("wind_dir", pd.Series(0, index=year_df.index))

    # Basic physical check: wind speed cannot be negative
    original_wind_speed = wind_speed.copy()
    negative_wind_count = (original_wind_speed < 0).sum()
    if negative_wind_count > 0:
        print(f"  Warning: {negative_wind_count} negative wind speed values fixed for {year}")
        wind_speed = wind_speed.clip(lower=0)  # Only fix negative values

    # Keep wind direction as-is, only fill NaN values
    wind_dir = wind_dir.fillna(0)  # Fill any NaN values with 0

    # Solar radiation - basic check: cannot be negative
    ghi = year_df.get("GHI", pd.Series(0.0, index=year_df.index)).clip(lower=0)
    dni = year_df.get("DNI", pd.Series(0.0, index=year_df.index)).clip(lower=0)
    dhi = year_df.get("DHI", pd.Series(0.0, index=year_df.index)).clip(lower=0)

    # Precipitation - basic check: cannot be negative
    precip_depth_mm = year_df.get("precip_depth", pd.Series(0.0, index=year_df.index)).clip(lower=0)
    precip_qty_hr = year_df.get("precip_duration", pd.Series(0.0, index=year_df.index)).clip(lower=0, upper=24)  # Duration cannot exceed 24 hours

    # Report basic data quality issues
    if negative_wind_count > 0:
        print(f"  Basic data quality check for {year}: {negative_wind_count} negative wind speed values corrected")

    # Build EPW rows
    rows = []
    for ts in year_df.index:
        Y = ts.year
        M = ts.month
        D = ts.day
        H = ts.hour + 1  # EPW uses 1-24
        Minute = 60
        Flags = 0
        db = float(temp_c.loc[ts])
        dp = float(dew_c.loc[ts])
        rhv = float(rh.loc[ts])
        p = float(pressure_pa.loc[ts])
        # Set unavailable radiative terms to 0/9999 as appropriate
        etr_h = 0
        etr_dn = 0
        ir_h = 0
        ghi_v = float(ghi.loc[ts])
        dni_v = float(dni.loc[ts])
        dhi_v = float(dhi.loc[ts])
        ghi_lux = 0
        dni_lux = 0
        dhi_lux = 0
        zen_lum = 0
        wdir = int(wind_dir.loc[ts]) if not pd.isna(wind_dir.loc[ts]) else 0
        wspd = float(wind_speed.loc[ts])
        tsky = 0
        osky = 0
        vis_km = 9999
        ceil_m = 99999
        wx_obs = 0
        wx_codes = 0
        pw_mm = 999
        aod = 0
        snow_cm = 0
        days_snow = 0
        albedo = 0
        lprecip_mm = float(precip_depth_mm.loc[ts])
        lprecip_hr = float(np.clip(precip_qty_hr.loc[ts], 0, 6))  # hourly qty cap

        row = [
            Y, M, D, H, Minute, Flags,
            f"{db:.1f}", f"{dp:.1f}", f"{rhv:.0f}", f"{p:.0f}",
            etr_h, etr_dn, ir_h,
            f"{ghi_v:.1f}", f"{dni_v:.1f}", f"{dhi_v:.1f}",
            ghi_lux, dni_lux, dhi_lux, zen_lum,
            wdir, f"{wspd:.1f}", tsky, osky, vis_km, ceil_m,
            wx_obs, wx_codes, pw_mm, aod, snow_cm, days_snow, albedo,
            f"{lprecip_mm:.1f}", f"{lprecip_hr:.1f}",
        ]
        rows.append(
            ",".join(map(str, row))
        )

    out_path.parent.mkdir(parents=True, exist_ok=True)
    header = _epw_header(location=location, lat=lat, lon=lon, tz=tz, elevation_m=elevation_m)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(header)
        for line in rows:
            f.write(line + "\n")

def process_csv_to_yearly_epw(cities=None, input_base=None, output_base=None):
    """
    Process hourly CSV files (2001-2100) for cities and generate yearly EPW files.
    Adapted to work with the backtesting bias corrected CSV format.

    Args:
        cities (dict): Dictionary of city configurations with metadata
        input_base (str or Path): Base path to input CSV files
        output_base (str or Path): Base path for output EPW files
    """
    # Default city configurations with location metadata
    if cities is None:
        cities = {
            'Los_Angeles': {
                'location': 'LosAngeles-CA-USA',
                'lat': 34.05,
                'lon': -118.25,
                'tz': -8.0,
                'elevation_m': 89.0
            },
            'Miami': {
                'location': 'Miami-FL-USA',
                'lat': 25.76,
                'lon': -80.19,
                'tz': -5.0,
                'elevation_m': 2.0
            },
            'Montreal': {
                'location': 'Montreal-PQ-CAN',
                'lat': 45.47,
                'lon': -73.74,
                'tz': -5.0,
                'elevation_m': 36.0
            },
            'Toronto': {
                'location': 'Toronto-ON-CAN',
                'lat': 43.68,
                'lon': -79.63,
                'tz': -5.0,
                'elevation_m': 173.0
            }
        }

    # Default paths
    if input_base is None:
        input_base = Path("data/backtesting_bias_corrected")
    else:
        input_base = Path(input_base)

    if output_base is None:
        output_base = Path("data/yearly_epw_files")
    else:
        output_base = Path(output_base)

    for city_name, city_config in cities.items():
        print(f"\nProcessing {city_name}...")

        # Read the CSV file
        csv_path = input_base / city_name / "epw_with_regimes_hourly.csv"
        if not csv_path.exists():
            print(f"Warning: CSV file not found for {city_name}: {csv_path}")
            continue

        print(f"Reading CSV file: {csv_path}")
        df = pd.read_csv(csv_path)

        # Convert datetime column to pandas datetime and set as index
        if 'datetime' in df.columns:
            df['datetime'] = pd.to_datetime(df['datetime'])
            df.set_index('datetime', inplace=True)
        else:
            # Create datetime from Year, Month, Day, Hour columns
            df['datetime'] = pd.to_datetime(df[['Year', 'Month', 'Day', 'Hour']])
            df.set_index('datetime', inplace=True)

        # Map CSV columns to expected format for EPW generation
        df_mapped = pd.DataFrame(index=df.index)

        # Temperature and humidity
        df_mapped['temp'] = df['DryBulb_C']
        df_mapped['relative_humidity'] = df['RelHum_pct']

        # Pressure
        df_mapped['pressure'] = df['Pressure_Pa']

        # Wind
        df_mapped['wind_speed'] = df['WindSpeed_mps']
        df_mapped['wind_dir'] = df['WindDir_deg']

        # Solar radiation
        df_mapped['GHI'] = df['GHI_Whm2']
        df_mapped['DNI'] = df['DNI_Whm2']
        df_mapped['DHI'] = df['DHI_Whm2']

        # Precipitation
        df_mapped['precip_depth'] = df['LiquidPrecip_mm']
        df_mapped['precip_duration'] = df['LiquidPrecip_hr']

        # Get unique years in the dataset
        years = df_mapped.index.year.unique()
        print(f"Found data for years: {min(years)} to {max(years)} ({len(years)} years)")

        # Create output directory for this city
        city_output_dir = output_base / city_name
        city_output_dir.mkdir(parents=True, exist_ok=True)

        # Generate EPW file for each year
        for year in sorted(years):
            try:
                output_path = city_output_dir / f"{city_name}_{year}.epw"
                print(f"Generating EPW for {year}: {output_path}")

                _write_epw_for_year(
                    df_mapped,
                    year,
                    output_path,
                    location=city_config['location'],
                    lat=city_config['lat'],
                    lon=city_config['lon'],
                    tz=city_config['tz'],
                    elevation_m=city_config['elevation_m']
                )

            except Exception as e:
                print(f"Error generating EPW for {city_name} {year}: {e}")
                continue

        print(f"Completed processing {city_name}")

    print(f"\nAll cities processed. EPW files saved to: {output_base}")


if __name__ == "__main__":
    # Process all cities and generate yearly EPW files
    cities = {
        'Los_Angeles': {
            'location': 'LosAngeles-CA-USA',
            'lat': 34.05,
            'lon': -118.25,
            'tz': -8.0,
            'elevation_m': 89.0
        },
        'Miami': {
            'location': 'Miami-FL-USA',
            'lat': 25.76,
            'lon': -80.19,
            'tz': -5.0,
            'elevation_m': 2.0
        },
        'Montreal': {
            'location': 'Montreal-PQ-CAN',
            'lat': 45.47,
            'lon': -73.74,
            'tz': -5.0,
            'elevation_m': 36.0
        },
        'Toronto': {
            'location': 'Toronto-ON-CAN',
            'lat': 43.68,
            'lon': -79.63,
            'tz': -5.0,
            'elevation_m': 173.0
        }
    }

    process_csv_to_yearly_epw(
        cities=cities,
        input_base="data/backtesting_bias_corrected",
        output_base="data/sMYM_epw"
    )
